### ISSUE TITLE
Remove Cody Cypert from Website

### ISSUE THREAD

**Issue by sydney-spiegel** [PrimitiveSocial/Peoples-Bank#1]
They need Cody Cypert removed from the website ASAP. He's on the Home Loan Center page.

https://peoplesbanktexas.com/home-loan-center/#loan-officers

<img width="2329" alt="Screen Shot 2019-12-20 at 12 28 51 PM" src="https://user-images.githubusercontent.com/53345439/71282954-9e4f1880-2324-11ea-9764-a11f8be001b0.png">

@jetercotton

**Comment by jetercotton** [comment]
@sydney-spiegel Done.
